name: Architect
version: '${version}'
main: cc.architect.Architect
api-version: '1.21'
authors: [japicraft]
website: https://crystalcaverns.net
dependencies:
  server:
    LuckPerms:
      load: BEFORE
    PlaceholderAPI:
      load: BEFORE
    HologramAPI:
      load: BEFORE
    packetevents:
      load: BEFORE