name: Architect
version: '${version}'
main: cc.architect.Architect
api-version: '1.20'
authors: [japicraft]
website: https://crystalcaverns.net
depend: [CommandPanels,LuckPerms]
commands:
  simulation:
    description: Main system command.
    permission: gameoflife.simulation